name: deployment
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "The environment to deploy to"
        required: true
        default: "TEST"
        type: choice
        options:
          - PRODUCTION
          - TEST
      service:
        description: "The service to deploy"
        required: true
        type: choice
        options:
          - account-service
          - document-worker-service
          - gateway-service
          - grading-service
          - payment-service
          - test-service
          - grading-platform
jobs:
  deploy_backend_service:
    # if: ${{ contains(fromJSON('["account-service", "document-worker-service" "gateway-service", "grading-service", "payment-service", "test-service"]'), github.event.inputs.service ) }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment }}
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Set short git commit SHA
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }}) 
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

      - name: Test
        run: |
          echo $COMMIT_SHORT_SHA
          echo ${{ env.COMMIT_SHORT_SHA }}
          echo ${{ secrets.K8S_CLUSTER_NAME }}

  deploy_grading_platform:
    if: github.event.inputs.service == 'grading-platform'
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment }}
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Test
        run: |
          echo ${{ github.event.inputs.service }}
          echo ${{ secrets.K8S_CLUSTER_NAME }}
