name: Tag Workflow Test

on:
  push:
    tags:
      - "grading-service/v*.*.*"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set ENV
        run: |
          echo "RELEASE_VERSION=$(echo ${GITHUB_REF#refs/*/} | cut -d "/" -f 2)" >> $GITHUB_ENV

      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
